### ISSUE TITLE
Internal error -3 in R_decompress1

### ISSUE THREAD

**Issue by PauloCirino** [njtierney/visdat#47]
Hey, Dude!

I'm getting this error : 
`Error in get(Info[i, 1], envir = env) : 
  lazy-load database '/usr/local/Cellar/r/3.3.3_1/R.framework/Versions/3.3/Resources/library/tidyr/R/tidyr.rdb' is corrupt
Além disso: Warning message:
In get(Info[i, 1], envir = env) : internal error -3 in R_decompress1`

Even in the example code : 
`vis_dat(airquality)`

**Comment by njtierney** [comment]
Hey mate!

It looks to me that you have a corrupt installation of tidyr, could you
perhaps try:

Running code examples from tidyr - do you get the same error?

Restarting R, and running `install.packages("tidyr")`, then does visdat
give the same error?

Let me know how you go!




On 19 May 2017 7:45 am, "Paulo Cirino Ribeiro Neto" <
notifications@github.com> wrote:

Hey, Dude!

I'm getting this error :
Error in get(Info[i, 1], envir = env) : lazy-load database
'/usr/local/Cellar/r/3.3.3_1/R.framework/Versions/3.3/
Resources/library/tidyr/R/tidyr.rdb' is corrupt Além disso: Warning
message: In get(Info[i, 1], envir = env) : internal error -3 in
R_decompress1

Even in the example code :
vis_dat(airquality)

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/njtierney/visdat/issues/47>, or mute the thread
