### ISSUE TITLE
Question: error about varying attributes

### ISSUE THREAD

**Issue by rosseji** [njtierney/visdat#48]
An error message:

```
Warning message:
attributes are not identical across measure variables; they will be dropped
```
Can you explain whats happening here? Is it that some variables have different metadata or classes?
And is dropped NA or removing?

**Comment by rosseji** [comment]
Great package though! You're a champ

**Comment by njtierney** [comment]
Hi Ross!

This will be fixed in an upcoming release - you can preview this on the [`fix-functionality`](https://github.com/njtierney/visdat/tree/fix-functionality) branch.

Basically the error is related to collating together factors in a tidyr::gather step, it is nothing to worry about, :)

Hopefully this should be on CRAN this coming weekend.

if that makes sense I'll close this issue, unless you have another question? :)
